# Colors (Noctalia)

[colors.bright]
black = '#555555'
blue = '#ffffff'
cyan = '#e6e6e6'
green = '#f2f2f0'
magenta = '#a6a6a6'
red = '#ff6b5e'
white = '#f2f2f0'
yellow = '#ffc94d'

[colors.cursor]
cursor = '#ffb000'
text = '#050505'

[colors.normal]
black = '#111111'
blue = '#f2f2f0'
cyan = '#c8c8c8'
green = '#b8b8b8'
magenta = '#8a8a8a'
red = '#ff3b30'
white = '#c8c8c8'
yellow = '#ffb000'

[colors.primary]
background = '#050505'
foreground = '#c8c8c8'

[colors.selection]
background = '#f2f2f0'
text = '#050505'
